<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "links".
 *
 * @property integer $link_id
 * @property string $full_address
 * @property string $link_hash
 */
class Links extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'links';
    }

    public static function getFullLinkByHash($hash){
        return Links::find()->where(['link_hash'=>$hash])->one();
    }

    public static function generateHash($link){
        return (string)crc32($link);
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['full_address'], 'required', 'message'=>'{attribute} не может быть пустой!'],
            #[['full_address'], 'url', 'validSchemes'=>['*'], 'message'=>'Неправильная ссылка'],
            [['full_address'], 'filter', 'filter' => 'trim'],
            [['full_address'], 'string', 'max' => 255],
            [['link_hash'], 'string', 'max' => 32],
        ];
    }

    public function beforeValidate()
    {
        #$this->full_address;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'link_id' => 'Link ID',
            'full_address' => 'Ссылка',
            'link_hash' => 'Link Hash',
        ];
    }
}
